### ISSUE TITLE
PDF not being analyzed when being deskewed by OCRMyPDF

### ISSUE THREAD

**Issue by thephilluk** [adlerweb/PdfQRSplit#6]
Hi,
I am running into a bit of a problem rn.

So I have my basic desktop Scanner, unfortunately this sometimes pulls in pages unevenly and the script doesn't recognize the Codes when skewed more than some angle.

So I tried running the PDF through OCRMyPDF in deskew mode, but then the Process is instant and the file is not being processed correctly.
 
I have attached both PDF Files (raw and deskewed / processed by OCRMyPDF)

Logs (Code Markdown not working for some reason, soooorry): 
--- Skewed PDF (about 5-10 Seconds)---
theph@DESKTOP-05K9I1J MINGW64 /d/a/Scan
$ python3 ./split.py -s "PhilipSplit" -v ./Scan.pdf
Processing file ./Scan.pdf containing 6 pages
  Analyzing page 1
  Analyzing page 2
    Found separator - writing 1 pages to split_0_0.pdf
  Analyzing page 3
  Analyzing page 4
  Analyzing page 5
    Found separator - writing 2 pages to split_0_1.pdf
  Analyzing page 6
    End of input - writing 1 pages to split_0_2.pdf
Split 1 given files into 3 files

--- Deskewing Pages ---
 ocrmypdf --deskew --output-type pdf ./Scan.pdf ./SkewPdf.pdf
Scanning contents: 100%|███████████████████████████████████████████████████| 6/6 [00:00<00:00, 102.26page/s]
Start processing 6 pages concurrently
    3 [tesseract] Empty page!!
    3 [tesseract] Empty page!!
    3 [tesseract] Empty page!!
OCR: 100%|██████████████████████████████████████████████████████████████| 6.0/6.0 [00:02<00:00,  2.16page/s]
Postprocessing...
Recompressing JPEGs: 0image [00:00, ?image/s]
Deflating JPEGs: 100%|████████████████████████████████████████████████████| 6/6 [00:00<00:00, 589.67image/s]
JBIG2: 0item [00:00, ?item/s]
Optimize ratio: 1.43 savings: 30.0%

--- Running on the edited PDF (basically instantly) ---
$ python3 ./split.py -s "PhilipSplit" -v ./SkewPdf.pdf
Processing file ./SkewPdf.pdf containing 6 pages
  Analyzing page 1
  Analyzing page 2
  Analyzing page 3
  Analyzing page 4
  Analyzing page 5
  Analyzing page 6
    End of input - writing 6 pages to split_0_0.pdf
Split 1 given files into 1 files

[Scan.pdf](https://github.com/adlerweb/PdfQRSplit/files/12032431/Scan.pdf)
[SkewPdf.pdf](https://github.com/adlerweb/PdfQRSplit/files/12032432/SkewPdf.pdf)

**Comment by adlerweb** [comment]
Thanks for the excellent bug description and sample files. Usually images inside PDF are stored either as raw bitmaps compressed with deflate or encoded as JPEG. Looks like ocrmypdf takes the "more is better"-approach and deflate-compresses the already compressed JPEG. While I do not know enough about PDF to implement a proper multi-filter-support matching "looks like JPEG" should work…
